### ISSUE TITLE
sample values of the 'niche' music don't go below 0

### ISSUE THREAD

**Issue by HybridDog** [demozoo/cowbell#10]
l tried that: https://demozoo.github.io/cowbell/
l noticed, when recording the niche music using audacity, that the sample values are never below 0, see this screenshot:
![2016-07-28-204258_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/17225343/d81a4ff4-5504-11e6-8529-88c64241f0b9.png)
It happened with Dancing Queen (PSG), Worlds Apart (STC), Summer Mood (PT3) and Squareland Story (VTX). The strange behaviour also causes an audible odd sound quality. The problem didn't happen with the 4 other music files.

Since l don't know those file types, l'm not sure if this behaviour is wrong or maybe deliberate.

**Comment by gasman** [comment]
This is expected behaviour. These file formats are for music written for the [AY / YM sound chip](https://en.wikipedia.org/wiki/General_Instrument_AY-3-8910), which works by summing / masking the outputs of several square-wave generators - each generator is zero or a positive voltage.

As a result, I don't think it's possible to eliminate this offset without introducing worse artefacts. (I know that other emulators have tried, and [broken the emulation as a result](https://sourceforge.net/p/fuse-emulator/patches/339/)...)

**Comment by HybridDog** [comment]
ok, thanks,

so you could double the volume of the music just by beginning at -1 instead of 0 and multiplying with 2. Of course to not cause clicks, when pressing play or stop it must be avoided to immediately jump to -1.

**Comment by gasman** [comment]
I don't think that will help - that'll just give you a different constant offset. For example, a track that only uses volume levels below 50% will give you a waveform where everything is below zero.

**Comment by HybridDog** [comment]
You're right, putting it to -1 may also make a DC offset removing plugin work badly
http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html#tth_sEc2.23
