### ISSUE TITLE
ASAP player should not assume 44100Hz playback

### ISSUE THREAD

**Issue by Some1NamedNate** [demozoo/cowbell#22]
Whenever an 8-bit Atari chiptune is played, its playback rate is forced to 60hz. Can you have it play back 50hz chiptunes?

**Comment by gasman** [comment]
Hi @Some1NamedNate - please can you give more details, including an example of a track that isn't being played correctly?

Also, I'm not sure what the relevance of ASAP version 4.0 is - do you have information to indicate that this bug is fixed in that version? I can't see anything relevant on http://asap.sourceforge.net/news.html.

**Comment by Some1NamedNate** [comment]
When you play a PAL (50Hz) SAP tune on Demozoo like [this one](https://demozoo.org/music/120937/), it's being played back to 60Hz (NTSC). When listened to with [ASAP](http://asap.sourceforge.net/) itself (i.e., [foobar2000](http://foobar2000.org) w/ the ASAP plugin), it plays back at 50hz.

**Comment by gasman** [comment]
The track you link to sounds the same when I play it through Demozoo and through the ASAP VLC plugin (on Mac OS). What's the exact difference you're hearing - just different tempo, or different pitch as well?

I'm wondering if the real problem is that your browser is using a 48000Hz sample rate natively, rather than 44100Hz - most of Cowbell's backends will work with whatever your browser provides, but I see that the SAP code has some hard-coded references to 44100 in it. If you look in your browser's Javascript console, do you get a "Warning: sample rate mismatch" message?

**Comment by pfusik** [comment]
@epi has contributed sample rate configuration. I'm going to release it in ASAP 6.0.0 later this summer.
